# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
